### ISSUE TITLE
sbt/TrackLevel

### ISSUE THREAD

**Issue by nsjames** [joost-de-vries/sbt-typescript#15]
I seem to be getting this error when using this plugin with play framework and activator.

**Error**
`java.lang.NoClassDefFoundError: sbt/TrackLevel`

**plugins.bat**
`addSbtPlugin("name.de-vries" % "sbt-typescript" % "0.3.0-beta.7")`

**sbt version**
`0.13.13`

If I change out the plugin with `ArpNetworking/sbt-typescript` for instance I can get a successful build.
Any ideas as to the cause of this?

This happens with a fresh clone of the play-angular2-typescript as well as a custom structure.

**Comment by joost-de-vries** [comment]
That class appeared in sbt with version `0.13.11`. 
If you have the same problem with `play-angular2-typescript` while I don't the differences seem to be either the version of the sbt-launcher. Or the JVM.
My sbt-launcher version was `0.13.9`. And I've upgraded to `0.13.13`. And it compiles and runs fine.

Can you upgrade your sbt-launcher and check your Java version?

I have to say though that `0.3.0-beta.7` of sbt-typescript doesn't play well with `play-angular2-typescript`. But that's because `sbt-tslint` doesn't support that typescript version yet. But you don't get the exception then that you're getting.

**Comment by joost-de-vries** [comment]
I think its because you have some sbt plugin that forces a lower version of sbt-web than sbt-typescript has been compiled against. See [this](https://github.com/sbt/sbt-web/commit/f2fe338b6ce87d29e2dc634f5b431561b70c9f44)

**Comment by mattcsully** [comment]
Latest versions exhibit the same issue with play-angular2-typescript-java v 0.2.0-beta.4
Play 2.5.3, JRE (build 1.8.0_121-b13)

**Comment by mattcsully** [comment]
PS C:\users\matt\play-angular2-typescript-java
> sbt "project play-angular2-typescript-java" clean "~ compile"
results in:
```
[info] Set current project to play-angular2-typescript-java (in build file:/C:/Users/matt/play-angular2-typescript-java/)
[error] Not a valid project ID: play-angular2-typescript-java
[error] project play-angular2-typescript-java
[error]                                      ^
```

**Comment by joost-de-vries** [comment]
@mattcsully can you contact the creator of `play-angular2-typescript-java`? 
I think it's a problem with using another sbt-web plugin that forces a lower version than sbt-typescript depends on. So it's probably the combination of sbt plugins in that project.
