### ISSUE TITLE
Keep paths specified in tsconfig.json

### ISSUE THREAD

**Issue by dbarashev** [joost-de-vries/sbt-typescript#17]
Hi, I am trying to use two root dirs for my TypeScript code in a Play application (`app/assets/javascripts` and `app/assets/test`) so that modules defined in the second dir were able to use modules defined in the first. This seems to work with plain `tsconfig.json+tsc` but not with sbt-typescript plugin.

Here is my tsconfig.json:
```
{
    "compilerOptions": {
        "baseUrl": "app/assets",
        "paths": {
            "*": [
                "javascripts/*",
                "test/*"
            ]
        },
        "rootDirs": [
            "app/assets/javascripts",
            "app/assets/test"
        ],
        "typeRoots": ["node_modules" ],
        "types": ["jquery", "requirejs", "qunit"],
        "allowJs": true,
        "target": "es5",
        "module": "amd",
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strictNullChecks": true
    },
    "include": [
        "**/*.ts"
    ],
    "exclude": [ "project/**" ]
}
```

It works just fine if compiled with plain `tsc`. However, when sbt-typescript is involved, it builds rootDirs on its own and I get `Compilation error[TS2307 Cannot find module 'module/sitting/inside/javascripts'.]`

Any ideas how to get it working with the current sbt-typescript or maybe fix the plugin so that it didn't ignore `rootDirs` from `tsconfig.json` ?

**Comment by joost-de-vries** [comment]
There's a beginning of support for test assets as you can tell from [this unit test](https://github.com/joost-de-vries/sbt-typescript/tree/master/src/sbt-test/sbt-typescript/testassets)
The status is that test assets can refer to main assets and that the typescript does compile.
Unfortunately the typescript compiler doesn't deal with what the right output path should be as soon as you move from rootDir to rootDirs. And [my function to move the output of tsc to the right path](https://github.com/joost-de-vries/sbt-typescript/blob/master/src/main/typescript/typescript.ts#L141) isn't correct yet: the unit test fails at this moment.
It's a bit of a hassle to write the typescript/node functions to reverse engineer te work that tsc doesn't do.
And since nobody was using the feature I never got around to it.

If you would like to give improving that function a go; a PR would be very welcome since I'd really like situations with multiple rootDirs to be solid.

As far as setting rootDirs from the tsconfig.json file: by choosing sbt to manage the compilation of typescript it follows that 'sbt-typescript' is responsible for knowing what the source and test directories are and providing them to the typescript compiler. 
That's the reason that setting those in tsconfig.json is ignored. Perhaps we should log a warning to point that out.

**Comment by dbarashev** [comment]
Thanks for the reply!
With respect to tsconfig.json: maybe just let user specify an option to ignore SBT settings? Currently you set  `rootDirs = node_modules` no matter what SBT thinks of `node_modules`, so why not allow user to do the same?

**Comment by joost-de-vries** [comment]
`rootDirs = node_modules` : that's actually not what the plugin does.

I'd like to support test assets as defined by sbt and multiproject build first.

You're welcome to help make that work.

**Comment by dbarashev** [comment]
Mia culpa! I mixed up rootDirs and paths, sorry.

I meant this line: 
https://github.com/joost-de-vries/sbt-typescript/blob/master/src/main/typescript/typescript.ts#L56

which replaces paths specified in tsconfig.json with, basically, node_modules.

**Comment by dbarashev** [comment]
I changed the title, sorry again for the confusion.

**Comment by joost-de-vries** [comment]
What would be possible without breaking the role of sbt is to merge the tsconfig.json settings that sbt-typescript manages with the ones in the projects tsconfig.json.
A PR would be welcome...
