### ISSUE TITLE
Enable to import Lodash In my project

### ISSUE THREAD

**Issue by Scipionh** [joost-de-vries/sbt-typescript#18]
Hey, in my build.sbt, I do have :

```
"org.webjars.npm" % "types__lodash" % "4.14.30",
"org.webjars.npm" % "lodash" % "4.17.2",
```

I haven't set anything regarding types in my tsconfig.json.
However, I do have used a folder used typings/browser.d.ts
where I set 
`///<reference path="./../target/web/web-modules/main/webjars/lib/types__lodash/lodash/index.d.ts"/>`
and in my built.sbt, I have set the following :
`typingsFile := Some(baseDirectory.value / "typings" / "browser.d.ts")`

It seems to work fine, but I am pretty sure that's not the right way to do it. Did I miss anything here ?

**Comment by joost-de-vries** [comment]
Which version of typescript / sbt-typescript are you using?

Tsc should be able to find  your `@types/lodash` type definitions without the `typingsFile` setting. That setting is no longer necessary since TS 2. 
The namespace import `///<reference ...` shouldn't be necessary either. You'll probably do a module import. Something like `import * as "_" from "lodash"`.
All this is not sbt-typescript specific by the way. In fact the [first google result gives great answers](http://stackoverflow.com/questions/34660265/importing-lodash-into-angular2-typescript-application).

So I'll go ahead and close this issue.
